name: freshpunk
description: "FreshPunk - Premium Meal Delivery Service. Fresh, healthy meals delivered to your door."
publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.2.0
  firebase_data_connect: ^0.2.1+1
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.0.3
  firebase_storage: ^13.0.3
  firebase_messaging: ^16.0.3
  firebase_app_check: ^0.4.1+2
  google_maps_flutter: ^2.9.0
  google_polyline_algorithm: ^3.1.0
  uuid: ^4.5.1
  geocoding: ^4.0.0
  geolocator: ^14.0.2
  http: ^1.2.2
  shared_preferences: ^2.3.2
  flutter_stripe: ^12.1.0
  dio: ^5.4.0
  flutter_local_notifications: ^19.5.0
  timezone: ^0.10.1
  local_auth: ^3.0.0
  url_launcher: ^6.3.0
  dart_jsonwebtoken: ^3.3.1
  provider: ^6.1.2
  cloud_functions: ^6.0.3
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^7.0.1
  permission_handler: ^12.0.1
  flutter_svg: ^2.0.10+1
  flutter_dotenv: ^6.0.0
  package_info_plus: ^8.0.2
  webview_flutter: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/meals/
    - assets/images/restaurants/
    - assets/icons/
    - assets/data/
